package prueba;

/**
 *
 * @author Jesús Alejandro Torres Ramírez
 */
public class MiNombre extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;

    /**
     * Creates new form MiNombre
     */
    public MiNombre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbName = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbApePat = new javax.swing.JLabel();
        jlbApeMat = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfApePat = new javax.swing.JTextField();
        jtfApeMat = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbName.setText("Name:");
        add(jlbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 32, -1, -1));

        jlbNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNombre.setText("Nombre");
        add(jlbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 88, -1, -1));

        jlbApePat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbApePat.setText("Apellido P");
        add(jlbApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 144, -1, -1));

        jlbApeMat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbApeMat.setText("Apellido M");
        add(jlbApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 205, -1, -1));

        jtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });
        add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 85, 132, -1));

        jtfApePat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfApePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApePatActionPerformed(evt);
            }
        });
        jtfApePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApePatKeyTyped(evt);
            }
        });
        add(jtfApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 144, 130, 30));

        jtfApeMat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfApeMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApeMatActionPerformed(evt);
            }
        });
        jtfApeMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApeMatKeyTyped(evt);
            }
        });
        add(jtfApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 202, 132, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed

    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfApePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApePatActionPerformed

    }//GEN-LAST:event_jtfApePatActionPerformed

    private void jtfApeMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApeMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApeMatActionPerformed

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        jlbName.setText(  jtfNombre.getText() + " " + jtfApePat.getText() + " " + jtfApeMat.getText());

    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfApePatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApePatKeyTyped
        jlbName.setText( jtfNombre.getText() + " " + jtfApePat.getText() + " " + jtfApeMat.getText());

    }//GEN-LAST:event_jtfApePatKeyTyped

    private void jtfApeMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApeMatKeyTyped
        jlbName.setText( jtfNombre.getText() + " " + jtfApePat.getText() + " " + jtfApeMat.getText());

    }//GEN-LAST:event_jtfApeMatKeyTyped

    @Override
    public void setObject(Object bean) {
        this.bean = bean;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbApeMat;
    private javax.swing.JLabel jlbApePat;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JTextField jtfApeMat;
    private javax.swing.JTextField jtfApePat;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
