/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicapersona;

/**
 *
 * @author Jesús Alejandro Torres Ramírez
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCurp = new javax.swing.JTextField();
        jLabelCurp = new javax.swing.JLabel();
        jLabelPaterno = new javax.swing.JLabel();
        jLabelMaterno = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPaterno = new javax.swing.JTextField();
        jTextFieldMaterno = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jTextFieldAnio = new javax.swing.JTextField();
        jTextFieldMes = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(656, 447));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCurp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCurpActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 270, 30));

        jLabelCurp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCurp.setText("Curp:");
        getContentPane().add(jLabelCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabelPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPaterno.setText("Paterno:");
        getContentPane().add(jLabelPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabelMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMaterno.setText("Materno:");
        getContentPane().add(jLabelMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Verificar CURP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jTextFieldPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 270, 30));

        jTextFieldMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, 30));

        jTextFieldEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 270, -1));

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha de nacimiento:");
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabelSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSexo.setText("Sexo:");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabelEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado:");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jTextFieldDia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 90, -1));

        jTextFieldAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 90, -1));

        jTextFieldMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 90, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 270, -1));

        jComboBoxSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "H" }));
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCurpActionPerformed

    private void jTextFieldPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaternoActionPerformed

    private void jTextFieldMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaternoActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCurp;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMaterno;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPaterno;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldCurp;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldMaterno;
    private javax.swing.JTextField jTextFieldMes;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPaterno;
    // End of variables declaration//GEN-END:variables
}
